#!/usr/bin/env python3
"""Import normalized node JSON into Xboard's `v2_server` table.

The script uses the local `mysql` CLI instead of a Python MySQL driver so it
can run directly on an Xboard server with minimal dependencies.
"""

from __future__ import annotations

import argparse
import json
import shlex
import subprocess
import sys
import time
from pathlib import Path
from typing import Any


DEFAULT_GROUP_NAMES = ["vip1", "vip2", "vip3"]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Import node JSON into Xboard.")
    parser.add_argument("input", help="Path to JSON generated by node_probe.py")
    parser.add_argument("--db-host", default="127.0.0.1")
    parser.add_argument("--db-port", default=3306, type=int)
    parser.add_argument("--db-name", default="xboard")
    parser.add_argument("--db-user", default="root")
    parser.add_argument("--db-password", required=True)
    parser.add_argument("--mysql-bin", default="mysql")
    parser.add_argument(
        "--groups",
        default=",".join(DEFAULT_GROUP_NAMES),
        help="Fallback group names, comma separated.",
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Actually write to the database. Without this flag the script only prints the SQL plan.",
    )
    parser.add_argument(
        "--force-insert",
        action="store_true",
        help="Do not try to update matching nodes; always insert new rows.",
    )
    return parser.parse_args()


def mysql_command(args: argparse.Namespace) -> list[str]:
    return [
        args.mysql_bin,
        f"--host={args.db_host}",
        f"--port={args.db_port}",
        f"--user={args.db_user}",
        f"--password={args.db_password}",
        "--batch",
        "--raw",
        "--skip-column-names",
        args.db_name,
    ]


def run_mysql(args: argparse.Namespace, sql: str) -> str:
    result = subprocess.run(
        mysql_command(args),
        input=sql,
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or "mysql command failed")
    return result.stdout.strip()


def sql_quote(value: Any) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, (int, float)):
        return str(value)
    text = str(value).replace("\\", "\\\\").replace("'", "\\'")
    return f"'{text}'"


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def find_group_table(args: argparse.Namespace) -> str:
    candidates = ["v2_server_group", "server_group", "v2_server_groups"]
    for table_name in candidates:
        output = run_mysql(args, f"SHOW TABLES LIKE {sql_quote(table_name)};")
        if output.strip() == table_name:
            return table_name
    raise RuntimeError("未找到权限组表，尝试过: " + ", ".join(candidates))


def get_table_columns(args: argparse.Namespace, table_name: str) -> set[str]:
    output = run_mysql(args, f"SHOW COLUMNS FROM `{table_name}`;")
    columns = set()
    for line in output.splitlines():
        if not line.strip():
            continue
        columns.add(line.split("\t", 1)[0])
    return columns


def get_group_id_map(args: argparse.Namespace, table_name: str) -> dict[str, str]:
    output = run_mysql(args, f"SELECT id, name FROM `{table_name}`;")
    mapping: dict[str, str] = {}
    for line in output.splitlines():
        if not line.strip():
            continue
        group_id, name = line.split("\t", 1)
        mapping[name] = str(group_id)
    return mapping


def resolve_group_ids(node: dict[str, Any], fallback_groups: list[str], group_map: dict[str, str]) -> list[str]:
    group_names = node.get("group_names") or fallback_groups
    missing = [name for name in group_names if name not in group_map]
    if missing:
        raise RuntimeError(f"权限组不存在: {', '.join(missing)}")
    return [group_map[name] for name in group_names]


def compact_json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"))


def build_row(node: dict[str, Any], group_ids: list[str], columns: set[str]) -> dict[str, Any]:
    now = int(time.time())
    host = node["host"]
    listen_port = int(node.get("listen_port") or node.get("server_port") or 0)
    server_port = int(node.get("server_port") or listen_port)
    network_settings = node.get("network_settings") or {}
    tags = node.get("tags") or []
    route_ids = node.get("route_ids") or []

    row: dict[str, Any] = {}
    field_map: dict[str, Any] = {
        "name": node["name"],
        "type": node.get("type") or node.get("protocol"),
        "host": host,
        "server_addr": host,
        "port": listen_port,
        "server_port": server_port,
        "parent_id": 0,
        "route_id": 0,
        "show": 1 if node.get("show", True) else 0,
        "status": int(node.get("status", 1)),
        "sort": int(node.get("sort", 0)),
        "rate": str(node.get("rate", "1")),
        "network": node.get("network") or network_settings.get("network") or "tcp",
        "networkSettings": compact_json(network_settings),
        "group_ids": compact_json([str(item) for item in group_ids]),
        "route_ids": compact_json(route_ids),
        "tags": compact_json(tags),
        "license": None,
        "created_at": now,
        "updated_at": now,
    }

    for key, value in field_map.items():
        if key in columns:
            row[key] = value
    return row


def find_existing_node_id(
    args: argparse.Namespace,
    table_name: str,
    node: dict[str, Any],
    columns: set[str],
) -> int | None:
    if "host" not in columns:
        return None

    host = node["host"]
    node_type = node.get("type") or node.get("protocol")
    server_port = int(node.get("server_port") or node.get("listen_port") or 0)

    filters = [f"type={sql_quote(node_type)}", f"host={sql_quote(host)}"]
    if "server_port" in columns:
        filters.append(f"server_port={server_port}")
    elif "port" in columns:
        filters.append(f"port={server_port}")
    else:
        filters.append(f"name={sql_quote(node['name'])}")

    sql = f"SELECT id FROM `{table_name}` WHERE {' AND '.join(filters)} ORDER BY id DESC LIMIT 1;"
    output = run_mysql(args, sql).strip()
    if not output:
        return None
    return int(output)


def build_insert_sql(table_name: str, row: dict[str, Any]) -> str:
    columns = ", ".join(f"`{key}`" for key in row)
    values = ", ".join(sql_quote(value) for value in row.values())
    return f"INSERT INTO `{table_name}` ({columns}) VALUES ({values});"


def build_update_sql(table_name: str, row: dict[str, Any], record_id: int) -> str:
    assignments = ", ".join(f"`{key}`={sql_quote(value)}" for key, value in row.items() if key != "created_at")
    return f"UPDATE `{table_name}` SET {assignments} WHERE id={record_id};"


def main() -> int:
    args = parse_args()
    input_path = Path(args.input).expanduser().resolve()
    payload = load_json(input_path)

    table_name = "v2_server"
    group_table = find_group_table(args)
    columns = get_table_columns(args, table_name)
    group_map = get_group_id_map(args, group_table)
    fallback_groups = [item.strip() for item in args.groups.split(",") if item.strip()]

    sql_statements: list[str] = []
    summaries: list[str] = []

    for node in payload.get("nodes", []):
        group_ids = resolve_group_ids(node, fallback_groups, group_map)
        row = build_row(node, group_ids, columns)
        existing_id = None if args.force_insert else find_existing_node_id(args, table_name, node, columns)
        if existing_id is None:
            sql_statements.append(build_insert_sql(table_name, row))
            summaries.append(f"INSERT {node['name']} ({node['host']}:{node.get('server_port')})")
        else:
            sql_statements.append(build_update_sql(table_name, row, existing_id))
            summaries.append(f"UPDATE #{existing_id} {node['name']} ({node['host']}:{node.get('server_port')})")

    if not sql_statements:
        print("JSON 中没有节点。", file=sys.stderr)
        return 1

    print("导入计划:")
    for summary in summaries:
        print(f"  - {summary}")

    if not args.apply:
        print()
        print("以下为待执行 SQL（当前为 dry-run）:")
        print("\n".join(sql_statements))
        print()
        print("确认无误后，重新加 `--apply` 执行。")
        return 0

    sql = "\n".join(sql_statements) + "\n"
    run_mysql(args, sql)
    print()
    print(f"已写入 {len(sql_statements)} 条 SQL 到 Xboard 数据库。")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
